const REQUEST_TO_SERVER_FOR_SERVER_LIST = 'REQUEST_TO_SERVER_FOR_SERVER_LIST'
const ERROR_TO_SERVER_FOR_SERVER_LIST = 'ERROR_TO_SERVER_FOR_SERVER_LIST'
const SUCCESS_REQUEST_TO_SERVER_FOR_SERVER_LIST =
  'SUCCESS_TO_SERVER_FOR_SERVER_LIST'

const SELECTION_SERVER_FOR_VIEW = 'SELECTION_SERVER_FOR_VIEW'

const OPEN_INPUT_FOR_CHANGE_VALUE_SERVER = 'OPEN_INPUT_FOR_CHANGE_VALUE_SERVER'
const CLOSE_INPUT_FOR_CHANGE_VALUE_SERVER =
  'CLOSE_INPUT_FOR_CHANGE_VALUE_SERVER'

const REQUEST_TO_SERVER_FOR_CHANGE_VALUE_SERVER =
  'REQUEST_TO_SERVER_FOR_CHANGE_VALUE_SERVER'
const SUCCESS_TO_SERVER_FOR_CHANGE_VALUE_SERVER =
  'SUCCESS_TO_SERVER_FOR_CHANGE_VALUE_SERVER'
const ERROR_TO_SERVER_FOR_CHANGE_VALUE_SERVER =
  'ERROR_TO_SERVER_FOR_CHANGE_VALUE_SERVER'

const CHANGE_NAME_SERVER = 'CHANGE_NAME_SERVER'
const CHANGE_NAME_SERVER_ERROR = 'CHANGE_NAME_SERVER_ERROR'
// const CLEAR_NAME_SERVER = 'ClEAR_NAME_SERVER'
const CHANGE_TYPE_SERVER = 'CHANGE_TYPE_SERVER'
// const CLEAR_TYPE_SERVER = 'CLEAR_TYPE_SERVER'

const InputWhichCanBeChanged = {
  server_name: 'server Name',
  server_type: 'server Type',
}

const typesOfServer = ['vds', 'dedicated', 'hosting', 'idle']

const optionInputWichChange = ['open', 'close', 'save']

export {
  CHANGE_TYPE_SERVER,
  // CLEAR_TYPE_SERVER,
  CHANGE_NAME_SERVER,
  CHANGE_NAME_SERVER_ERROR,
  // CLEAR_NAME_SERVER,
  InputWhichCanBeChanged,
  optionInputWichChange,
  typesOfServer,
  SUCCESS_TO_SERVER_FOR_CHANGE_VALUE_SERVER,
  REQUEST_TO_SERVER_FOR_CHANGE_VALUE_SERVER,
  ERROR_TO_SERVER_FOR_CHANGE_VALUE_SERVER,
  CLOSE_INPUT_FOR_CHANGE_VALUE_SERVER,
  REQUEST_TO_SERVER_FOR_SERVER_LIST,
  SUCCESS_REQUEST_TO_SERVER_FOR_SERVER_LIST,
  ERROR_TO_SERVER_FOR_SERVER_LIST,
  SELECTION_SERVER_FOR_VIEW,
  OPEN_INPUT_FOR_CHANGE_VALUE_SERVER,
}
