const REQUEST_TO_SERVER_FOR_SERVER_LIST = 'REQUEST_TO_SERVER_FOR_SERVER_LIST'
const ERROR_TO_SERVER_FOR_SERVER_LIST = 'ERROR_TO_SERVER_FOR_SERVER_LIST'
const SUCCESS_REQUEST_TO_SERVER_FOR_SERVER_LIST =
  'SUCCESS_TO_SERVER_FOR_SERVER_LIST'

const SELECTION_SERVER_FOR_VIEW = 'SELECTION_SERVER_FOR_VIEW'

const OPEN_INPUT_FOR_CHANGE_VALUE_SERVER = 'OPEN_INPUT_FOR_CHANGE_VALUE_SERVER'
const CLOSE_INPUT_FOR_CHANGE_VALUE_SERVER =
  'CLOSE_INPUT_FOR_CHANGE_VALUE_SERVER'

const UPDATE_NAME_OF_SERVER = 'UPDATE_NAME_OF_SERVER'
const UPDATE_TYPE_OF_SERVER = 'UPDATE_TYPE_OF_SERVER'

const InputWhichCanBeChanged = {
  server_name: 'server Name',
  server_type: 'server Type',
}

const typesOfServer = {
  1: 'vds',
  2: 'dedicated',
  3: 'hosting',
}

const optionInputWichChange = ['open', 'close']

export {
  InputWhichCanBeChanged,
  optionInputWichChange,
  typesOfServer,
  CLOSE_INPUT_FOR_CHANGE_VALUE_SERVER,
  REQUEST_TO_SERVER_FOR_SERVER_LIST,
  SUCCESS_REQUEST_TO_SERVER_FOR_SERVER_LIST,
  ERROR_TO_SERVER_FOR_SERVER_LIST,
  SELECTION_SERVER_FOR_VIEW,
  UPDATE_NAME_OF_SERVER,
  UPDATE_TYPE_OF_SERVER,
  OPEN_INPUT_FOR_CHANGE_VALUE_SERVER,
}
